--------------- Users Table ------------
  CREATE TABLE "AOA"."OAUTH_USERS" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(32 BYTE), 
	"PASSWORD" VARCHAR2(256 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(64 BYTE), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"START_DATE" VARCHAR2(16 BYTE), 
	"ENABLED" NUMBER, 
	"LAST_PASSWORD" VARCHAR2(40 BYTE), 
	"EXPIRED" NUMBER, 
	 CONSTRAINT "APP_USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

------------------------ User Roles Table ------------------

  CREATE TABLE "AOA"."OAUTH_USER_ROLES" 
   (	"USERNAME" VARCHAR2(36 BYTE), 
	"ROLE" VARCHAR2(36 BYTE), 
	"USER_ROLE_ID" VARCHAR2(36 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-------------- Tokens Table-----------------

  CREATE TABLE "SYS"."OAUTH_ACCESS_TOKEN" 
   (	"TOKEN_ID" VARCHAR2(256 BYTE), 
	"TOKEN" BLOB, 
	"AUTHENTICATION_ID" VARCHAR2(256 BYTE), 
	"USER_NAME" VARCHAR2(256 BYTE), 
	"CLIENT_ID" VARCHAR2(256 BYTE), 
	"AUTHENTICATION" BLOB, 
	"REFRESH_TOKEN" VARCHAR2(256 BYTE), 
	 PRIMARY KEY ("AUTHENTICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("TOKEN") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUTHENTICATION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

------------------------ API Client Details Table ----------------

  CREATE TABLE "SYS"."OAUTH_CLIENT_DETAILS" 
   (	"CLIENT_ID" VARCHAR2(256 BYTE), 
	"RESOURCE_IDS" VARCHAR2(256 BYTE), 
	"CLIENT_SECRET" VARCHAR2(256 BYTE), 
	"SCOPE" VARCHAR2(256 BYTE), 
	"AUTHORIZED_GRANT_TYPES" VARCHAR2(256 BYTE), 
	"WEB_SERVER_REDIRECT_URI" VARCHAR2(256 BYTE), 
	"AUTHORITIES" VARCHAR2(256 BYTE), 
	"ACCESS_TOKEN_VALIDITY" NUMBER(38,0), 
	"REFRESH_TOKEN_VALIDITY" NUMBER(38,0), 
	"ADDITIONAL_INFORMATION" VARCHAR2(2048 BYTE), 
	"AUTOAPPROVE" VARCHAR2(256 BYTE), 
	 PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-------------------- Refresh Token Table -------------------

  CREATE TABLE "SYS"."OAUTH_CLIENT_DETAILS" 
   (	"CLIENT_ID" VARCHAR2(256 BYTE), 
	"RESOURCE_IDS" VARCHAR2(256 BYTE), 
	"CLIENT_SECRET" VARCHAR2(256 BYTE), 
	"SCOPE" VARCHAR2(256 BYTE), 
	"AUTHORIZED_GRANT_TYPES" VARCHAR2(256 BYTE), 
	"WEB_SERVER_REDIRECT_URI" VARCHAR2(256 BYTE), 
	"AUTHORITIES" VARCHAR2(256 BYTE), 
	"ACCESS_TOKEN_VALIDITY" NUMBER(38,0), 
	"REFRESH_TOKEN_VALIDITY" NUMBER(38,0), 
	"ADDITIONAL_INFORMATION" VARCHAR2(2048 BYTE), 
	"AUTOAPPROVE" VARCHAR2(256 BYTE), 
	 PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

